# Generated by Django 2.2.4 on 2020-04-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvShowsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Show',
        ),
    ]
