# Generated by Django 2.2.4 on 2020-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShowsApp', '0002_auto_20200421_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
